removing auto restart for production/test

diff --git a/Install b/Install
--- a/Install
+++ b/Install
@@ -93,27 +93,27 @@ printf "\nSoftware Install completed\n"
 
 
 # Do extra steps if we are building for production or test
-if [ "$INSTALL_TYPE" == "prod" ] || [ "$INSTALL_TYPE" == "test" ]; then
+#if [ "$INSTALL_TYPE" == "prod" ] || [ "$INSTALL_TYPE" == "test" ]; then
+#
+#	printf "\n$INSTALL_TYPE environment detected...\n"
+#	source bin/activate
+#	source Configuration
+#	cd admin
 
-	printf "\n$INSTALL_TYPE environment detected...\n"
-	source bin/activate
-	source Configuration
-	cd admin
+#	# run acceptance tests on test environment to make sure this
+#	# version of code doesn't break anything
+#	if [ "$INSTALL_TYPE" == "test" ]; then
+#	
+#		printf "\nRunning Acceptance Tests\n"
+#		./runAcceptanceTests
+#		if [ $? -ne 0 ]; then
+#			echo "Acceptance Tests Failed"
+#			exit 1
+#		fi
 
-	# run acceptance tests on test environment to make sure this
-	# version of code doesn't break anything
-	if [ "$INSTALL_TYPE" == "test" ]; then
-	
-		printf "\nRunning Acceptance Tests\n"
-		./runAcceptanceTests
-		if [ $? -ne 0 ]; then
-			echo "Acceptance Tests Failed"
-			exit 1
-		fi
+#	fi
 
-	fi
+#	printf "\nRestarting Server\n"
+#	./restartserver.sh
 
-	printf "\nRestarting Server\n"
-	./restartserver.sh
-
-fi
+#fi
